In [1]:
"""
1) Прочитайте главы 2-3 из книги "Spark: The Definitive Guide"
2) Установите библиотеки numpy, pandas, matplotlib и seasborn.
Для этого введите в консоли:

source ~/Work/bin/activate
pip3 install numpy
pip3 install pandas
pip3 install matplotlib
pip3 install seaborn

3) Скачайте датасет TikTok_songs_2022.csv по ссылке https://www.kaggle.com/datasets/sveta151/tiktok-popular-songs-2022
4) Выполните задания 1-5 с помощью SQL и методов DataFrame.
5) Ответьте на вопросы в задании 6.
"""


'\n1) Прочитайте главы 2-3 из книги "Spark: The Definitive Guide"\n2) Установите библиотеки numpy, pandas, matplotlib и seasborn.\nДля этого введите в консоли:\n\nsource ~/Work/bin/activate\npip3 install numpy\npip3 install pandas\npip3 install matplotlib\npip3 install seaborn\n\n3) Скачайте датасет TikTok_songs_2022.csv по ссылке https://www.kaggle.com/datasets/sveta151/tiktok-popular-songs-2022\n4) Выполните задания 1-5 с помощью SQL и методов DataFrame.\n5) Ответьте на вопросы в задании 6.\n'

In [2]:
#!pip install numpy pandas matplotlib seaborn


In [3]:
# Создаем SparkSession
import pyspark
from pyspark.sql import SparkSession

spark = SparkSession.builder.master("local[1]").appName("SparkApp").getOrCreate()


22/09/15 00:09:39 WARN Utils: Your hostname, student-VirtualBox resolves to a loopback address: 127.0.1.1; using 10.0.2.15 instead (on interface enp0s3)
22/09/15 00:09:39 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address


Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).


22/09/15 00:09:40 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable


In [4]:
# Загружаем датасет https://www.kaggle.com/datasets/sveta151/tiktok-popular-songs-2022
tiktokData2022 = (
    spark.read.option("inferSchema", "true")
    .option("header", "true")
    .csv("TikTok_songs_2022.csv")
)

tiktokData2022.createOrReplaceTempView("TikTok_songs_2022")


In [5]:
# 0: Получите таблицу из  5 названий треков с их исполнителями.

# +--------------------+-------------+
# |          track_name|  artist_name|
# +--------------------+-------------+
# |Running Up That H...|    Kate Bush|
# |           As It Was| Harry Styles|
# |             Sunroof|  Nicky Youre|
# |          Heat Waves|Glass Animals|
# |     About Damn Time|        Lizzo|
# +--------------------+-------------+

from pyspark.sql.functions import desc

sqlWay = spark.sql(
    """
SELECT track_name,artist_name
FROM TikTok_songs_2022
LIMIT 5
"""
)

dataFrameWay = tiktokData2022.select("track_name", "artist_name").limit(5)

sqlWay.show()
dataFrameWay.show()


+--------------------+-------------+
|          track_name|  artist_name|
+--------------------+-------------+
|Running Up That H...|    Kate Bush|
|           As It Was| Harry Styles|
|             Sunroof|  Nicky Youre|
|          Heat Waves|Glass Animals|
|     About Damn Time|        Lizzo|
+--------------------+-------------+

+--------------------+-------------+
|          track_name|  artist_name|
+--------------------+-------------+
|Running Up That H...|    Kate Bush|
|           As It Was| Harry Styles|
|             Sunroof|  Nicky Youre|
|          Heat Waves|Glass Animals|
|     About Damn Time|        Lizzo|
+--------------------+-------------+



In [6]:
# 1: Получите список исполнителей с популярностью больше 90%

# ['Drake', 'Harry Styles', 'The Weeknd']

sqlWay = spark.sql(
    """
SELECT DISTINCT artist_name FROM TikTok_songs_2022
WHERE artist_pop > 90
"""
)

dataFrameWay = (
    tiktokData2022.select("artist_name")
    .where(tiktokData2022.artist_pop > 90)
    .distinct()
)

print(sqlWay.rdd.map(lambda x: x[0]).collect())
print(dataFrameWay.rdd.map(lambda x: x[0]).collect())


['Drake', 'Harry Styles', 'The Weeknd']
['Drake', 'Harry Styles', 'The Weeknd']


In [7]:
# 2: Выведите список исполнителей и количество их треков в порядке уменьшения.
# Ограничьте выборку исполнителями, у которых не менее 3 треков в наборе данных.

# +--------------+----------------+
# |   artist_name|number_of_tracks|
# +--------------+----------------+
# |      Doja Cat|               8|
# |        Coopex|               6|
# |     Dame Dame|               5|
# |     Lil Nas X|               4|
# |Alex Alexander|               4|
# |       YES YES|               4|
# |         Farux|               4|
# | Ariana Grande|               3|
# |       Astelle|               3|
# |  Alex D'Rosso|               3|
# |      Dua Lipa|               3|
# |    The Weeknd|               3|
# |     Nito-Onna|               3|
# |     Pop Smoke|               3|
# | The Kid LAROI|               3|
# +--------------+----------------+

from pyspark.sql.functions import desc, count

sqlWay = spark.sql(
    """
SELECT artist_name, count(*) as number_of_tracks
FROM TikTok_songs_2022
GROUP BY artist_name
HAVING number_of_tracks >= 3
ORDER BY number_of_tracks DESC
"""
)

dataFrameWay = (
    tiktokData2022.groupBy("artist_name")
    .agg(count("*").alias("number_of_tracks"))
    .where("number_of_tracks >= 3")
    .orderBy("number_of_tracks", ascending=False)
)

sqlWay.show()
dataFrameWay.show()


+--------------+----------------+
|   artist_name|number_of_tracks|
+--------------+----------------+
|      Doja Cat|               8|
|        Coopex|               6|
|     Dame Dame|               5|
|     Lil Nas X|               4|
|Alex Alexander|               4|
|       YES YES|               4|
|         Farux|               4|
| Ariana Grande|               3|
|       Astelle|               3|
|  Alex D'Rosso|               3|
|      Dua Lipa|               3|
|    The Weeknd|               3|
|     Nito-Onna|               3|
|     Pop Smoke|               3|
| The Kid LAROI|               3|
+--------------+----------------+

+--------------+----------------+
|   artist_name|number_of_tracks|
+--------------+----------------+
|      Doja Cat|               8|
|        Coopex|               6|
|     Dame Dame|               5|
|     Lil Nas X|               4|
|Alex Alexander|               4|
|       YES YES|               4|
|         Farux|               4|
| Ariana Gran

In [8]:
# 3: Выведите список названий треков, средняя громкость которых лежит в диапазоне от -10 до -9 Дб.

# ['Glimpse of Us', 'Left and Right (Charlie Puth) [feat. Jung Kook of BTS] - Sped Up Version',
# 'Frozen', "Can't Get You Out of My Head", 'I Hate U', 'I AM WOMAN', 'Buss It', 'Whatever You Like',
# 'MONEY', 'Freaks', 'telepatía', 'Falling Down', 'Party Girl', 'Skechers', 'Good Looking']

sqlWay = spark.sql(
    """
SELECT track_name FROM TikTok_songs_2022
WHERE loudness BETWEEN -10 AND -9
"""
)

dataFrameWay = tiktokData2022.select("track_name").where(
    tiktokData2022.loudness.between(-10, -9)
)

print(sqlWay.rdd.map(lambda x: x[0]).collect())
print(dataFrameWay.rdd.map(lambda x: x[0]).collect())


['Glimpse of Us', 'Left and Right (Charlie Puth) [feat. Jung Kook of BTS] - Sped Up Version', 'Frozen', "Can't Get You Out of My Head", 'I Hate U', 'I AM WOMAN', 'Buss It', 'Whatever You Like', 'MONEY', 'Freaks', 'telepatía', 'Falling Down', 'Party Girl', 'Skechers', 'Good Looking']
['Glimpse of Us', 'Left and Right (Charlie Puth) [feat. Jung Kook of BTS] - Sped Up Version', 'Frozen', "Can't Get You Out of My Head", 'I Hate U', 'I AM WOMAN', 'Buss It', 'Whatever You Like', 'MONEY', 'Freaks', 'telepatía', 'Falling Down', 'Party Girl', 'Skechers', 'Good Looking']


In [9]:
# 4: Выведите список треков, в названиях которых есть слово "love" (без учета регистра).

# ['Another Love', 'love nwantiti (ah ah ah)', 'Tainted Love', 'Looking for Love', 'Free Falling Love',
# 'Electric Love', 'Feel Your Love', 'What You Know Bout Love', 'Savage Love (Laxed - Siren Beat)',
# 'Love Me Again', 'Lovely']

from pyspark.sql.functions import lower

sqlWay = spark.sql(
    """
SELECT track_name FROM TikTok_songs_2022
WHERE LOWER(track_name) LIKE '%love%'
"""
)

dataFrameWay = tiktokData2022.select("track_name").where(
    lower(tiktokData2022.track_name).like("%love%")
)

print(sqlWay.rdd.map(lambda x: x[0]).collect())
print(dataFrameWay.rdd.map(lambda x: x[0]).collect())


['Another Love', 'love nwantiti (ah ah ah)', 'Tainted Love', 'Looking for Love', 'Free Falling Love', 'Electric Love', 'Feel Your Love', 'What You Know Bout Love', 'Savage Love (Laxed - Siren Beat)', 'Love Me Again', 'Lovely']
['Another Love', 'love nwantiti (ah ah ah)', 'Tainted Love', 'Looking for Love', 'Free Falling Love', 'Electric Love', 'Feel Your Love', 'What You Know Bout Love', 'Savage Love (Laxed - Siren Beat)', 'Love Me Again', 'Lovely']


In [10]:
# 5: Получите таблицу из песен Арианы Гранде и Astelle. Отсортируйте их по примеру ниже.

# +--------------------+-------------+
# |          track_name|  artist_name|
# +--------------------+-------------+
# |               34+35|Ariana Grande|
# |motive (with Doja...|Ariana Grande|
# |           positions|Ariana Grande|
# |             Dreamer|      Astelle|
# |           K Boy Bye|      Astelle|
# |                Paid|      Astelle|
# +--------------------+-------------+

sqlWay = spark.sql(
    """
SELECT track_name, artist_name
FROM TikTok_songs_2022
WHERE artist_name in ("Ariana Grande", "Astelle")
ORDER BY artist_name, album
"""
)

dataFrameWay = (
    tiktokData2022.select("track_name", "artist_name")
    .where(tiktokData2022.artist_name.isin("Ariana Grande", "Astelle"))
    .orderBy("artist_name", "track_name")
)

sqlWay.show()
dataFrameWay.show()


+--------------------+-------------+
|          track_name|  artist_name|
+--------------------+-------------+
|               34+35|Ariana Grande|
|motive (with Doja...|Ariana Grande|
|           positions|Ariana Grande|
|             Dreamer|      Astelle|
|           K Boy Bye|      Astelle|
|                Paid|      Astelle|
+--------------------+-------------+

+--------------------+-------------+
|          track_name|  artist_name|
+--------------------+-------------+
|               34+35|Ariana Grande|
|motive (with Doja...|Ariana Grande|
|           positions|Ariana Grande|
|             Dreamer|      Astelle|
|           K Boy Bye|      Astelle|
|                Paid|      Astelle|
+--------------------+-------------+



In [11]:
# 6: Какую задачу решает приведенный ниже код?
# Ответ: Разделяет все треки на 20 групп по их параметрам
# В чем суть метода K средних?
# В пространстве признаков случайно выбираются N центров кластеров
# (Объект будет относится к группе того кластера к центру которого он находится ближе всего)
# Итеративно центры кластеров смещаются в сторону центра массы относящихся к ним в данный момент объектов
# Процесс прекращается когда их смещение становится меньше eps
# В результате получаются готовые кластеры
# Какие еще существуют методы машинного обучения для решения данной задачи?
# Affinity propagation, Сдвиг среднего значения, Спектральная кластеризация и другие
# Какие выводы можно сделать о полученных группах?
# Трудно ответить на этот вопрос
# Интуитивно возникает гипотиза о том что треки в пределах одной группы должны быть похожи между собой
# Однако анализ показал что треки относящиеся к альбомам из которых представлено >= 3 трека оказались распределены по разным группам
# Planet Her - 4 трека в 3 группах
# Shoot For The Stars Aim For The Moon - 3 трека в 3 группах
# То же можно сказать о треках относящихся к одному исполнителю если рассматривать тех у которых >= 5 треков
# Doja Cat - 8 треков, 5 групп
# Coopex - 6 треков, 5 групп
# Dame Dame - 5 треков, 4 группы
# Прослушивание треков из самых двух самых маленьких групп так же не привело к какому-то пониманию
# В группе 13 - 2 трека:
# Xilo - Aesthetic - это Хип-хоп/рэп
# Peachy! - Falling for U - это R&B/соул
# единственное что в них похоже - фоновая музыка
# В группе 9 - 3 трека:
# Freaks - Surf Curse - это Инди-поп
# Write This Down (Instrumental) - SoulChef - это Инструментальный хип-хоп
# Astronomia - Vicetone - танцевальная музыка(та самая)
# как и в жанрах на слух какая-либо близость между ними не обнаружена

from pyspark.ml.feature import VectorAssembler
from pyspark.ml.feature import StringIndexer
from pyspark.ml import Pipeline
from pyspark.ml.clustering import KMeans
from pyspark.sql import Row
from pyspark.ml.feature import MinMaxScaler
from IPython.display import display
import numpy as np

k = 20

np.set_printoptions(precision=3, suppress=True)

columns_to_scale = [
    "danceability",
    "energy",
    "speechiness",
    "acousticness",
    "instrumentalness",
    "liveness",
    "valence",
    "duration_ms",
    "tempo",
    "track_pop",
]
assemblers = [
    VectorAssembler(inputCols=[col], outputCol=col + "_vec") for col in columns_to_scale
]
scalers = [
    MinMaxScaler(inputCol=col + "_vec", outputCol=col + "_scaled")
    for col in columns_to_scale
]

vectorAssembler = (
    VectorAssembler()
    .setInputCols(
        [
            "danceability_scaled",
            "energy_scaled",
            "speechiness_scaled",
            "acousticness_scaled",
            "instrumentalness_scaled",
            "liveness_scaled",
            "valence_scaled",
            "duration_ms_scaled",
            "tempo_scaled",
            "track_pop_scaled",
        ]
    )
    .setOutputCol("features")
)

transformationPipeline = Pipeline().setStages(assemblers + scalers + [vectorAssembler])

fittedPipeline = transformationPipeline.fit(tiktokData2022)
transformedDF = fittedPipeline.transform(tiktokData2022)

kmeans = KMeans().setK(k).setSeed(300)

kmModel = kmeans.fit(transformedDF)

df_pred = kmModel.transform(transformedDF)

centers = kmModel.clusterCenters()
for i in range(0, k):
    print("group " + str(i))
    print(centers[i])
    df = (
        df_pred.selectExpr(
            "track_name",
            "artist_name",
            "album",
            "danceability",
            "energy",
            "speechiness",
            "acousticness",
            "instrumentalness",
            "liveness",
            "valence",
            "duration_ms",
            "tempo",
            "track_pop",
        )
        .where("prediction = " + str(i))
        .toPandas()
    )
    display(df)


group 0
[0.745 0.779 0.497 0.064 0.001 0.139 0.551 0.327 0.455 0.582]


track_name    artist_name  \
0                        Riptide  Viva La Panda   
1               When You're Gone       Paradigm   
2              THATS WHAT I WANT      Lil Nas X   
3                        We Know   JAM & Philly   
4            When You Were Young          Amero   
5   Bundles (feat. Taylor Girlz)   Kayla Nicole   
6                           Paid        Astelle   
7                             Up        Cardi B   
8   Best Friend (feat. Doja Cat)       Saweetie   
9                       Rude Boy        YES YES   
10                           Fly   Alex D'Rosso   
11                      The Boss         Coopex   
12           Cool for the Summer   Alex D'Rosso   
13                    Boss Bitch       Doja Cat   
14                        Tap In       Saweetie   
15                           BOP         DaBaby   

                                      album  danceability  energy  \
0                                   Riptide         0.621   0.847   
1                          When You're Gone         0.783   0.753   
2                                   MONTERO         0.737   0.846   
3                                   We Know         0.871   0.819   
4                       When You Were Young         0.806   0.845   
5              Bundles (feat. Taylor Girlz)         0.939   0.682   
6                                      Paid         0.861   0.631   
7                         Up (Instrumental)         0.868   0.795   
8   Best Friend (feat. Doja Cat) [Remix EP]         0.840   0.766   
9                                  Rude Boy         0.739   0.734   
10                                      Fly         0.676   0.842   
11                                 The Boss         0.734   0.789   
12                      Cool for the Summer         0.805   0.871   
13                               Boss Bitch         0.707   0.955   
14                                   Tap In         0.954   0.696   
15                                     KIRK         0.769   0.787   

    speechiness  acousticness  instrumentalness  liveness  valence  \
0         0.278       0.05840          0.000001    0.1090    0.373   
1         0.325       0.01170          0.000000    0.1390    0.663   
2         0.220       0.00614          0.000000    0.0486    0.546   
3         0.256       0.14200          0.000000    0.1060    0.712   
4         0.190       0.08250          0.000000    0.2600    0.508   
5         0.306       0.00152          0.000000    0.0552    0.584   
6         0.230       0.01880          0.000283    0.0954    0.675   
7         0.269       0.00120          0.019300    0.0461    0.819   
8         0.136       0.00302          0.000004    0.0684    0.402   
9         0.259       0.02420          0.000000    0.0921    0.471   
10        0.239       0.05780          0.001370    0.2090    0.388   
11        0.243       0.08090          0.000115    0.2150    0.258   
12        0.286       0.17700          0.000008    0.2660    0.443   
13        0.222       0.12700          0.000000    0.2020    0.575   
14        0.204       0.00576          0.000498    0.0754    0.432   
15        0.367       0.18900          0.000000    0.1290    0.836   

    duration_ms    tempo  track_pop  
0        172431  101.996         51  
1        145161  124.036         53  
2        143901   87.981         88  
3        198982  112.114         39  
4        128095  125.998         31  
5        154806  130.022         67  
6        180923  117.993         39  
7        156945  166.000         70  
8        155884   94.018         45  
9        174858  101.995         50  
10       134857  140.142         53  
11       133810  125.992         47  
12       171696  136.010         49  
13       134240  125.989         78  
14       139413  100.036         67  
15       159715  126.770         76

group 1
[0.59  0.768 0.107 0.077 0.003 0.204 0.433 0.351 0.515 0.547]


track_name       artist_name  \
0                 Flex On My Ex (with Bankrol Hayden)          KillBunk   
1                                          That Bxtch     Taylor Watson   
2                                     Warning / Signs    Matvey Emerson   
3                                            Serenity              Shab   
4                                        Tainted Love          Thatsimo   
5                                               Crazy      Alex D'Rosso   
6                                              Dinero  Trinidad Cardona   
7                                         Ocean Drive          Harddope   
8                                         Young Folks    Jungle Jonsson   
9                                         Complicated         Nito-Onna   
10                             Astronaut In The Ocean       Masked Wolf   
11                                                Why              Padé   
12                                     Heart of Glass         Nito-Onna   
13                                       Mr. Saxobeat         Nito-Onna   
14                                    Pumped Up Kicks            Madism   
15                      Ready 4 Luv - TMLH Summer Mix          CAZZETTE   
16  Wellerman - Sea Shanty / 220 KID x Billen Ted ...      Nathan Evans   
17                                          Follow Me            Senhit   
18                                        Wicked Game           YES YES   
19                                          K Boy Bye           Astelle   
20                                       Play With Me         Ana Shine   
21                                            Forever      Nadia Gattas   
22                                     Feel Your Love        Yusuf Alev   
23                                       Say It Right            Coopex   
24                                 One too Many Times               JRL   
25                                            Forever        Gianni Blu   
26                                         What's up?            LeXxìv   
27                                         Let Her Go             LANDR   

                                                album  danceability  energy  \
0                 Flex On My Ex (with Bankrol Hayden)         0.619   0.707   
1                                          That Bxtch         0.645   0.681   
2                                     Warning / Signs         0.712   0.829   
3                                            Serenity         0.688   0.595   
4                                        Tainted Love         0.646   0.765   
5                                               Crazy         0.681   0.865   
6                                              Dinero         0.708   0.782   
7                                         Ocean Drive         0.645   0.868   
8                                         Young Folks         0.750   0.731   
9                                         Complicated         0.724   0.692   
10                             Astronaut In The Ocean         0.778   0.695   
11                               Why (with WLHELMINA)         0.610   0.902   
12                                     Heart of Glass         0.750   0.838   
13                                       Mr. Saxobeat         0.696   0.899   
14                                    Pumped Up Kicks         0.669   0.687   
15                      Ready 4 Luv (TMLH Summer Mix)         0.679   0.869   
16  Wellerman (Sea Shanty / 220 KID x Billen Ted R...         0.722   0.893   
17                                          Follow Me         0.707   0.867   
18                                        Wicked Game         0.755   0.835   
19                                          K Boy Bye         0.547   0.865   
20                                       Play With Me         0.714   0.666   
21                                            Forever         0.750   0.879   
22                                     Feel Your L

group 2
[0.8   0.408 0.213 0.317 0.018 0.348 0.78  0.429 0.294 0.774]


track_name    artist_name                                  album  \
0      Build a Bitch   Bella Poarch                          Build a Bitch   
1         Ain't Shit       Doja Cat                             Planet Her   
2  Rover (feat. DTG)          S1mba                      Rover (feat. DTG)   
3     Therefore I Am  Billie Eilish                         Therefore I Am   
4    Boys Ain't Shit       SAYGRACE                        Boys Ain't Shit   
5            The Box    Roddy Ricch  Please Excuse Me for Being Antisocial   
6       Toosie Slide          Drake                   Dark Lane Demo Tapes   
7        Sunday Best       Surfaces                     Where the Light Is   

   danceability  energy  speechiness  acousticness  instrumentalness  \
0         0.855   0.463       0.0367         0.217          0.000018   
1         0.855   0.488       0.2080         0.506          0.000000   
2         0.613   0.624       0.2060         0.496          0.000000   
3         0.889   0.340       0.0697         0.218          0.130000   
4         0.826   0.615       0.1370         0.435          0.006310   
5         0.896   0.586       0.0559         0.104          0.000000   
6         0.830   0.490       0.2090         0.289          0.000003   
7         0.878   0.525       0.0578         0.183          0.000000   

   liveness  valence  duration_ms    tempo  track_pop  
0    0.3470    0.866       122773  102.931         76  
1    0.3470    0.619       174253  124.097         81  
2    0.2830    0.803       167917   62.948         78  
3    0.0550    0.716       174321   94.009         75  
4    0.3340    0.841       175884  102.999         64  
5    0.7900    0.642       196653  116.971         81  
6    0.1130    0.845       247059   81.604         69  
7    0.0714    0.694       158571  112.022         77

group 3
[0.666 0.553 0.094 0.442 0.021 0.196 0.654 0.531 0.63  0.791]


track_name       artist_name  \
0                                          As It Was      Harry Styles   
1                                          Bad Habit        Steve Lacy   
2                                 Would I Lie to You            MISERO   
3                                           good 4 u    Olivia Rodrigo   
4                                           Lemonade    Internet Money   
5                   Savage Love (Laxed - Siren Beat)         Jawsh 685   
6                                          Play Date  Melanie Martinez   
7                                         Supalonely             BENEE   
8                           Intentions (feat. Quavo)     Justin Bieber   
9                                     Baby I'm Yours          Breakbot   
10  Girls Like You (feat. Cardi B) - Cardi B Version          Maroon 5   
11                                        Without Me            Halsey   

                                        album  danceability  energy  \
0                                   As It Was         0.520   0.731   
1                               Gemini Rights         0.686   0.494   
2                          Would I Lie to You         0.796   0.731   
3                                        SOUR         0.563   0.664   
4   Lemonade (feat. Gunna, Don Toliver & NAV)         0.799   0.660   
5            Savage Love (Laxed - Siren Beat)         0.767   0.481   
6                   Cry Baby (Deluxe Edition)         0.680   0.729   
7                              STELLA & STEVE         0.863   0.631   
8                                     Changes         0.806   0.546   
9                                By Your Side         0.829   0.792   
10                    Red Pill Blues (Deluxe)         0.851   0.541   
11                                 Without Me         0.752   0.488   

    speechiness  acousticness  instrumentalness  liveness  valence  \
0        0.0557         0.342          0.001010    0.3110    0.662   
1        0.0355         0.613          0.000058    0.4020    0.700   
2        0.0669         0.529          0.239000    0.1430    0.498   
3        0.1540         0.335          0.000000    0.0849    0.688   
4        0.0790         0.256          0.000000    0.1110    0.471   
5        0.0803         0.234          0.000000    0.2690    0.761   
6        0.0475         0.612          0.000000    0.2240    0.446   
7        0.0534         0.305          0.000030    0.1230    0.817   
8        0.0575         0.300          0.000000    0.1020    0.874   
9        0.0668         0.726          0.000006    0.1220    0.758   
10       0.0505         0.568          0.000000    0.1300    0.448   
11       0.0705         0.297          0.000009    0.0936    0.533   

    duration_ms    tempo  track_pop  
0        167303  173.930         96  
1        232067  168.946         86  
2        174000  120.067         51  
3        178147  166.928         88  
4        195429  140.040         76  
5        171375  150.076         77  
6        179867  123.970         78  
7        223480  128.977         72  
8        212867  147.986         77  
9        215507  118.050         69  
10       235545  124.959         74  
11       201661  136.041         77

group 4
[0.262 0.616 0.15  0.034 0.    0.217 0.303 0.456 0.857 0.852]


track_name      artist_name  \
0      STAY (with Justin Bieber)    The Kid LAROI   
1            MIDDLE OF THE NIGHT       Elley Duhé   
2                           SNAP        Rosa Linn   
3                          Oh No           Kreepa   
4   Down Under (feat. Colin Hay)            Luude   
5                Blinding Lights       The Weeknd   
6  Jimmy Cooks (feat. 21 Savage)            Drake   
7                   Good Looking  Suki Waterhouse   

                          album  danceability  energy  speechiness  \
0     STAY (with Justin Bieber)         0.591   0.764       0.0483   
1           MIDDLE OF THE NIGHT         0.410   0.611       0.0467   
2                          SNAP         0.563   0.639       0.0684   
3                   Cold As Ice         0.541   0.527       0.1470   
4  Down Under (feat. Colin Hay)         0.308   0.861       0.1720   
5                   After Hours         0.514   0.730       0.0598   
6           Honestly, Nevermind         0.529   0.673       0.1750   
7                  Good Looking         0.377   0.558       0.0299   

   acousticness  instrumentalness  liveness  valence  duration_ms    tempo  \
0      0.038300          0.000000    0.1030   0.4780       141806  169.928   
1      0.022800          0.000000    0.1160   0.0899       184448  185.727   
2      0.107000          0.000011    0.4460   0.5180       179551  169.985   
3      0.002790          0.000509    0.2860   0.4290       166504  176.123   
4      0.012000          0.001030    0.2770   0.0386       158774  171.966   
5      0.001460          0.000095    0.0897   0.3340       200040  171.005   
6      0.000307          0.000002    0.0930   0.3660       218365  165.921   
7      0.078900          0.000342    0.1250   0.2670       214800  149.971   

   track_pop  
0         89  
1         91  
2         89  
3         58  
4         72  
5         90  
6         92  
7         80

group 5
[0.741 0.595 0.228 0.266 0.    0.258 0.672 0.372 0.523 0.078]


track_name           artist_name  \
0                    Fever - Remix                  XY&O   
1                     credit union               Kinrose   
2   MONTERO (Call Me By Your Name)             Lil Nas X   
3                             Lost           Frank Ocean   
4                 Looking for Love  Asketa & Natan Chaim   
5                          Buss It           Erica Banks   
6                             Lies             Dame Dame   
7                        positions         Ariana Grande   
8                        Slow Down                Coopex   
9           Mood (feat. iann dior)              24kGoldn   
10                    Backyard Boy     Claire Rosinkranz   
11                    WHATS POPPIN           Jack Harlow   
12                      The Git Up          Blanco Brown   
13                 hot girl bummer             blackbear   

                             album  danceability  energy  speechiness  \
0                    Fever (Remix)         0.782   0.586       0.0567   
1                     credit union         0.776   0.656       0.1300   
2   MONTERO (Call Me By Your Name)         0.610   0.508       0.1520   
3                   channel ORANGE         0.912   0.594       0.2260   
4                 Looking for Love         0.748   0.894       0.0998   
5                          Buss It         0.918   0.434       0.1730   
6                             Lies         0.823   0.771       0.0365   
7                        positions         0.736   0.802       0.0864   
8                        Slow Down         0.715   0.720       0.1930   
9           Mood (feat. iann dior)         0.700   0.722       0.0369   
10         BeVerly Hills BoYfRiEnd         0.819   0.642       0.1890   
11                    WHATS POPPIN         0.923   0.604       0.2450   
12                      The Git Up         0.847   0.678       0.1090   
13                 hot girl bummer         0.778   0.559       0.0776   

    acousticness  instrumentalness  liveness  valence  duration_ms    tempo  \
0         0.0608          0.004090    0.1150    0.724       156000  120.018   
1         0.3290          0.000000    0.1190    0.649       183465  148.950   
2         0.2970          0.000000    0.3840    0.758       137876  178.818   
3         0.0319          0.001220    0.1230    0.514       234093  123.070   
4         0.3110          0.000029    0.2390    0.503       148000  120.004   
5         0.5690          0.000003    0.1230    0.750       188735  109.997   
6         0.6270          0.001010    0.2710    0.658       156885  122.015   
7         0.4680          0.000000    0.0940    0.675       172325  144.005   
8         0.1340          0.000000    0.3660    0.410       138779  128.048   
9         0.2210          0.000000    0.2720    0.756       140526   90.989   
10        0.3360          0.000000    0.0735    0.452       129241  138.026   
11        0.0170          0.000000    0.2720    0.826       139741  145.062   
12        0.0669          0.000000    0.2740    0.811       200594   97.984   
13        0.1280          0.000000    0.3990    0.678       185093  129.989   

    track_pop  
0           0  
1          32  
2           4  
3           0  
4           0  
5           0  
6          37  
7           3  
8           0  
9          18  
10          0  
11          4  
12          3  
13          5

group 6
[0.688 0.635 0.086 0.13  0.02  0.12  0.783 0.359 0.519 0.56 ]


track_name     artist_name                 album  \
0                  Sunroof     Nicky Youre               Sunroof   
1     Being Good Is Boring       Jena Rose  Being Good Is Boring   
2                 The Plan     Arman Aydin              The Plan   
3                  Dreamer         Astelle               Dreamer   
4               On My Way!            P.S.            On My Way!   
5             I Wanna Know  Alex Alexander          I Wanna Know   
6            Moi... Lolita        Monaldin         Moi... Lolita   
7             Good Morning            P.S.          Good Morning   
8                 Memories          Coopex              Memories   
9              Say My Name         Why Not           Say My Name   
10     Leave The Door Open      Bruno Mars   Leave The Door Open   
11                Vacation     Dirty Heads              Vacation   
12       Whatever You Like            DLAY     Whatever You Like   
13          Work from Home          Coopex        Work from Home   
14                 Whoopty              CJ               Whoopty   
15  motive (with Doja Cat)   Ariana Grande    Positions (Deluxe)   
16           dirty laundry       blackbear             deadroses   
17                 HOLIDAY       Lil Nas X               HOLIDAY   
18               On My Way  Alex Alexander             On My Way   
19               Let It Go       Dame Dame             Let It Go   
20                 INFERNO       Sub Urban               INFERNO   

    danceability  energy  speechiness  acousticness  instrumentalness  \
0          0.768   0.716       0.0404       0.35000          0.000000   
1          0.767   0.758       0.0840       0.03680          0.000000   
2          0.812   0.653       0.0361       0.00590          0.000000   
3          0.744   0.848       0.0993       0.08110          0.000011   
4          0.797   0.666       0.0363       0.16700          0.000131   
5          0.772   0.754       0.0500       0.34800          0.397000   
6          0.796   0.660       0.0505       0.05310          0.000027   
7          0.732   0.511       0.0413       0.15000          0.000009   
8          0.745   0.862       0.1160       0.33500          0.000623   
9          0.773   0.740       0.0315       0.00779          0.000025   
10         0.586   0.616       0.0324       0.18200          0.000000   
11         0.736   0.751       0.0340       0.03810          0.000000   
12         0.687   0.679       0.0432       0.10900          0.000986   
13         0.845   0.669       0.0658       0.18100          0.003470   
14         0.719   0.648       0.1250       0.20000          0.000000   
15         0.789   0.742       0.0652       0.06810          0.000000   
16         0.766   0.640       0.0345       0.05100          0.000000   
17         0.810   0.511       0.1640       0.12000          0.000000   
18         0.670   0.544       0.0252       0.04290          0.000000   
19         0.769   0.796       0.0564       0.02790          0.000002   
20         0.820   0.611       0.1220       0.07660          0.000025   

    liveness  valence  duration_ms    tempo  track_pop  
0     0.1500    0.841       163026  131.430         44  
1     0.0682    0.844       160982  111.986         55  
2     0.1050    0.864       135484  124.034         58  
3     0.0889    0.823       178913  150.056         42  
4     0.1040    0.855       177080  119.021         54  
5     0.0784    0.880       149787  112.043         52  
6     0.3190    0.735       158312  109.920         49  
7     0.0590    0.691       161423  171.907         50  
8     0.1020    0.738       138453  123.979         64  
9     0.1500    0.659       160026  125.981         54  
10    0.0927    0.719       242096  148.088         31  
11    0.1050    0.839       209722  150.064         67  
12    0.1040    0.614       144677  123.976         49  
13    0.0897    0.860       151680  125.014         54  
14    0.1270    0.660       123263  140.201         74  


group 7
[0.502 0.791 0.174 0.122 0.    0.689 0.474 0.359 0.516 0.434]


track_name        artist_name  \
0                     Bad Habits         Ed Sheeran   
1                  Leap of Faith     Alex Alexander   
2   Running To You (feat. Caden)              VINAI   
3   She Wolf (Falling to Pieces)            YES YES   
4                      The Hills              Farux   
5              You Don't Know Me          Dame Dame   
6              Beauty And A Beat             Glamii   
7              Moves Like Jagger        Timemachine   
8                      As It Was     Michael Shynes   
9                    Wild & Free             Nander   
10                       Kiss Me      Lucas Estrada   
11                     Rather Be           Cabuizee   
12                        DÁKITI          Dame Dame   
13        When the Sun Goes Down  Martin van Lectro   
14           California Dreaming               Jorm   

                           album  danceability  energy  speechiness  \
0                     Bad Habits         0.808   0.897       0.0348   
1                  Leap of Faith         0.557   0.802       0.0541   
2   Running To You (feat. Caden)         0.579   0.727       0.0399   
3   She Wolf (Falling to Pieces)         0.592   0.719       0.0452   
4                      The Hills         0.656   0.778       0.2650   
5              You Don't Know Me         0.701   0.836       0.2750   
6              Beauty And A Beat         0.746   0.866       0.1480   
7              Moves Like Jagger         0.552   0.831       0.1940   
8                      As It Was         0.595   0.812       0.0481   
9                    Wild & Free         0.474   0.722       0.0355   
10                       Kiss Me         0.588   0.685       0.0624   
11                     Rather Be         0.706   0.895       0.1480   
12                        DÁKITI         0.726   0.815       0.1010   
13        When the Sun Goes Down         0.544   0.748       0.0865   
14           California Dreaming         0.717   0.865       0.0307   

    acousticness  instrumentalness  liveness  valence  duration_ms    tempo  \
0        0.04690          0.000031     0.364    0.591       231041  126.026   
1        0.00924          0.000708     0.569    0.778       191080  169.893   
2        0.03210          0.000000     0.714    0.246       183091  124.090   
3        0.00858          0.000000     0.635    0.169       171028  125.030   
4        0.40000          0.000000     0.533    0.736       129717  125.916   
5        0.03040          0.000143     0.635    0.373       157320  124.953   
6        0.12400          0.000013     0.596    0.519       138750  128.054   
7        0.09050          0.000026     0.440    0.733       199687  127.851   
8        0.00321          0.000001     0.397    0.483       124571  104.980   
9        0.06040          0.000000     0.584    0.274       149231  155.941   
10       0.37400          0.000155     0.581    0.122       146669  107.938   
11       0.29900          0.000000     0.480    0.556       163884  120.978   
12       0.20600          0.000000     0.631    0.627       147367  121.975   
13       0.06460          0.000000     0.519    0.391       148999  123.752   
14       0.02220          0.001200     0.605    0.487       152323  124.048   

    track_pop  
0          22  
1          51  
2          65  
3           0  
4          48  
5          49  
6          36  
7          46  
8          46  
9          39  
10         47  
11         46  
12         47  
13         37  
14         53

group 8
[0.537 0.693 0.103 0.092 0.009 0.327 0.524 0.6   0.407 0.814]


track_name          artist_name  \
0                                      Afraid To Feel            LF SYSTEM   
1                                   Betty (Get Money)           Yung Gravy   
2                                   House of Memories  Panic! At The Disco   
3                                             Beggin'             Måneskin   
4              Peaches (feat. Daniel Caesar & Giveon)        Justin Bieber   
5                                     Sweater Weather    The Neighbourhood   
6                                       Electric Love                BØRNS   
7   "More Than A Woman - From ""Saturday Night Fev...             Bee Gees   
8            Cupid's Chokehold / Breakfast in America     Gym Class Heroes   
9                                               Freak             Doja Cat   
10                                     Break My Heart             Dua Lipa   
11                                      Later Bitches     The Prince Karma   
12                                           That Way         Lil Uzi Vert   
13                                            ROXANNE       Arizona Zervas   
14                                         Dandelions              Ruth B.   

                              album  danceability  energy  speechiness  \
0                    Afraid To Feel         0.578   0.912       0.1140   
1                 Betty (Get Money)         0.723   0.772       0.0792   
2               Death of a Bachelor         0.506   0.817       0.0335   
3                            Chosen         0.714   0.800       0.0504   
4                           Justice         0.677   0.696       0.1190   
5                       I Love You.         0.612   0.807       0.0336   
6                          Dopamine         0.611   0.797       0.0533   
7   How Can You Mend A Broken Heart         0.601   0.703       0.0379   
8           The Papercut Chronicles         0.720   0.744       0.1200   
9                             Freak         0.688   0.716       0.0385   
10                 Future Nostalgia         0.730   0.729       0.0884   
11                    Later Bitches         0.769   0.518       0.1020   
12                         That Way         0.719   0.611       0.0403   
13                          ROXANNE         0.621   0.601       0.1480   
14                       Safe Haven         0.609   0.692       0.0259   

    acousticness  instrumentalness  liveness  valence  duration_ms    tempo  \
0       0.016600          0.003620    0.2730    0.680       177525  127.870   
1       0.005240          0.000012    0.3670    0.580       146471  102.004   
2       0.002720          0.000000    0.0486    0.506       208707  109.952   
3       0.127000          0.000000    0.3590    0.589       211560  134.002   
4       0.321000          0.000000    0.4200    0.464       198082   90.030   
5       0.049500          0.017700    0.1010    0.398       240400  124.053   
6       0.005430          0.001370    0.2600    0.518       218107  120.041   
7       0.175000          0.000084    0.5710    0.673       196213  106.164   
8       0.237000          0.000000    0.2550    0.619       243773   78.953   
9       0.096900          0.000000    0.0989    0.373       284480  116.912   
10      0.167000          0.000001    0.3490    0.467       221820  113.011   
11      0.000573          0.108000    0.3420    0.504       247976  121.116   
12      0.058200          0.000000    0.1550    0.489       212354  129.962   
13      0.052200          0.000000    0.4600    0.457       163636  116.735   
14      0.015700          0.000000    0.0864    0.454       233720  116.959   

    track_pop  
0          86  
1          87  
2          86  
3          86  
4          86  
5          90  
6          82  
7          76  
8          77  
9          72  
10         78  
11         49  
12         62  
13         78  
14         90

group 9
[0.459 0.892 0.081 0.003 0.883 0.207 0.509 0.432 0.56  0.502]


track_name artist_name                    album  \
0                          Freaks  Surf Curse                   Freaks   
1  Write This Down (Instrumental)    SoulChef  Escapism: Instrumentals   
2                      Astronomia    Vicetone               Astronomia   

   danceability  energy  speechiness  acousticness  instrumentalness  \
0         0.345   0.941       0.0466      0.000038             0.633   
1         0.826   0.738       0.0444      0.003550             0.939   
2         0.653   0.945       0.0960      0.005610             0.915   

   liveness  valence  duration_ms    tempo  track_pop  
0    0.0511    0.407       147062  179.626         85  
1    0.0633    0.781       188421   93.005          1  
2    0.4390    0.325       198095  126.093         60

group 10
[0.712 0.734 0.09  0.085 0.    0.141 0.84  0.531 0.37  0.834]


track_name          artist_name  \
0                                     About Damn Time                Lizzo   
1                   INDUSTRY BABY (feat. Jack Harlow)            Lil Nas X   
2                          Bam Bam (feat. Ed Sheeran)       Camila Cabello   
3         1, 2, 3 (feat. Jason Derulo & De La Ghetto)          Sofía Reyes   
4                                  Late Night Talking         Harry Styles   
5                                              MAMIII              Becky G   
6                             Cold Heart - PNAU Remix           Elton John   
7                          edamame (feat. Rich Brian)                bbno$   
8              Ameno Amapiano Remix (You Wanna Bamba)           Goya Menor   
9                                               Woman             Doja Cat   
10                           Kiss Me More (feat. SZA)             Doja Cat   
11                Jalebi Baby (Tesher x Jason Derulo)               Tesher   
12         Better Days (NEIKED x Mae Muller x Polo G)               NEIKED   
13                                          Thot Shit  Megan Thee Stallion   
14     Beautiful Mistakes (feat. Megan Thee Stallion)             Maroon 5   
15                          Levitating (feat. DaBaby)             Dua Lipa   
16  Friday (feat. Mufasa & Hypeman) - Dopamine Re-...                Riton   
17                                     Wait a Minute!               WILLOW   
18   Banana (feat. Shaggy) - DJ FLe - Minisiren Remix             Conkarah   
19                                    Don't Start Now             Dua Lipa   
20                                             Say So             Doja Cat   
21                                       In Your Eyes           The Weeknd   
22                  I Don't Care (with Justin Bieber)           Ed Sheeran   
23                         The Less I Know The Better          Tame Impala   

                                                album  danceability  energy  \
0                                     About Damn Time         0.836   0.743   
1                   INDUSTRY BABY (feat. Jack Harlow)         0.736   0.704   
2                                             Familia         0.756   0.697   
3         1, 2, 3 (feat. Jason Derulo & De La Ghetto)         0.792   0.895   
4                                       Harry's House         0.714   0.728   
5                                              MAMIII         0.843   0.700   
6                               The Lockdown Sessions         0.795   0.800   
7                          edamame (feat. Rich Brian)         0.815   0.848   
8              Ameno Amapiano Remix (You Wanna Bamba)         0.807   0.898   
9                                          Planet Her         0.824   0.764   
10                           Kiss Me More (feat. SZA)         0.762   0.701   
11                Jalebi Baby (Tesher x Jason Derulo)         0.691   0.829   
12         Better Days (NEIKED x Mae Muller x Polo G)         0.717   0.671   
13                                          Thot Shit         0.950   0.693   
14                                     JORDI (Deluxe)         0.713   0.676   
15                                   Future Nostalgia         0.702   0.825   
16  Friday (feat. Mufasa & Hypeman) [Dopamine Re-E...         0.824   0.862   
17                                       ARDIPITHECUS         0.764   0.705   
18   Banana (feat. Shaggy) [DJ FLe - Minisiren Remix]         0.824   0.854   
19                                    Don't Start Now         0.794   0.793   
20                                           Hot Pink         0.787   0.673   
21                                        After Hours         0.667   0.719   
22                  I Don't Care (with Justin Bieber)         0.798   0.675   
23                                           Currents         0.640   0.740   

    speechiness  acousticness  instrumentalness  liveness  valence  \
0        0.0656       0.09950          0.00000

group 11
[0.351 0.39  0.071 0.712 0.    0.304 0.204 0.692 0.554 0.823]


track_name      artist_name  \
0  Running Up That Hill (A Deal With God)        Kate Bush   
1                           Glimpse of Us             Joji   
2                       Until I Found You  Stephen Sanchez   
3                            Another Love        Tom Odell   
4                     Talking to the Moon       Bruno Mars   
5                         drivers license   Olivia Rodrigo   
6                               Good Days              SZA   
7        death bed (coffee for your head)            Powfu   

                              album  danceability  energy  speechiness  \
0                    Hounds Of Love         0.629   0.547       0.0550   
1                     Glimpse of Us         0.440   0.317       0.0531   
2                 Until I Found You         0.539   0.508       0.0288   
3            Long Way Down (Deluxe)         0.445   0.537       0.0400   
4              Doo-Wops & Hooligans         0.498   0.590       0.0320   
5                   drivers license         0.585   0.436       0.0601   
6                         Good Days         0.436   0.655       0.0583   
7  death bed (coffee for your head)         0.726   0.431       0.1350   

   acousticness  instrumentalness  liveness  valence  duration_ms    tempo  \
0         0.720          0.003140    0.0604   0.1970       298933  108.375   
1         0.891          0.000005    0.1410   0.2680       233456  169.914   
2         0.727          0.000000    0.1740   0.2270       177720  101.358   
3         0.695          0.000017    0.0944   0.1310       244360  122.769   
4         0.511          0.000000    0.1070   0.0784       217867  145.867   
5         0.721          0.000013    0.1050   0.1320       242014  143.874   
6         0.499          0.000008    0.6880   0.4120       279204  121.002   
7         0.731          0.000000    0.6960   0.3480       173333  144.026   

   track_pop  
0         95  
1         97  
2         90  
3         89  
4         76  
5         29  
6         81  
7         82

group 12
[0.663 0.522 0.127 0.205 0.002 0.139 0.382 0.422 0.332 0.841]


track_name     artist_name  \
0                                          Heat Waves   Glass Animals   
1                                         First Class     Jack Harlow   
2                                             abcdefu           GAYLE   
3                                            Envolver          Anitta   
4                                      Thousand Miles   The Kid LAROI   
5                        Cooped Up (with Roddy Ricch)     Post Malone   
6                                              Frozen         Madonna   
7                                 Meet Me At Our Spot     THE ANXIETY   
8                            love nwantiti (ah ah ah)            CKay   
9   SAD GIRLZ LUV MONEY Remix (feat. Kali Uchis an...         Amaarae   
10                                       Life Goes On     Oliver Tree   
11                                          The Motto          Tiësto   
12                                       Need to Know        Doja Cat   
13                                         Todo De Ti  Rauw Alejandro   
14                                          You Right        Doja Cat   
15                                       The Business          Tiësto   
16                                          telepatía      Kali Uchis   
17                                        WITHOUT YOU   The Kid LAROI   
18                       ROCKSTAR (feat. Roddy Ricch)          DaBaby   
19                                              34+35   Ariana Grande   
20            For The Night (feat. Lil Baby & DaBaby)       Pop Smoke   
21                                         THE SCOTTS      THE SCOTTS   
22                                    Blueberry Faygo       Lil Mosey   
23                              Be Kind (with Halsey)      Marshmello   
24                                          Plug Walk    Rich The Kid   

                                                album  danceability  energy  \
0                          Dreamland (+ Bonus Levels)         0.761   0.525   
1                                         First Class         0.905   0.563   
2                                             abcdefu         0.695   0.540   
3                                            Envolver         0.812   0.736   
4                                      Thousand Miles         0.376   0.657   
5                                           Cooped Up         0.669   0.773   
6                                              Frozen         0.706   0.633   
7                                         THE ANXIETY         0.773   0.470   
8                                      CKay The First         0.727   0.739   
9   SAD GIRLZ LUV MONEY Remix (feat. Kali Uchis an...         0.870   0.523   
10  Ugly is Beautiful: Shorter, Thicker & Uglier (...         0.700   0.490   
11                                          The Motto         0.754   0.763   
12                                         Planet Her         0.664   0.609   
13                                         Todo De Ti         0.780   0.718   
14                                         Planet Her         0.828   0.621   
15                                       The Business         0.798   0.620   
16            Sin Miedo (del Amor y Otros Demonios) ∞         0.653   0.524   
17                                 F*CK LOVE (SAVAGE)         0.662   0.413   
18                                   BLAME IT ON BABY         0.746   0.690   
19                                          Positions         0.830   0.585   
20               Shoot For The Stars Aim For The Moon         0.823   0.586   
21                                         THE SCOTTS         0.716   0.537   
22                                 Certified Hitmaker         0.774   0.554   
23                              Be Kind (with Halsey)         0.630   0.633   
24                                 The World Is Yours         0.876   0.519   

    speechiness  acousticness  instrumentalness  liveness  valence  \
0        0.0944    

group 13
[0.47  0.354 0.882 0.885 0.136 0.103 0.421 0.26  0.494 0.015]


track_name artist_name          album  danceability  energy  \
0      Aesthetic        Xilo      Aesthetic         0.714   0.594   
1  Falling for U     Peachy!  Falling for U         0.516   0.358   

   speechiness  acousticness  instrumentalness  liveness  valence  \
0        0.430         0.965          0.255000    0.1290    0.450   
1        0.424         0.743          0.000001    0.0813    0.397   

   duration_ms    tempo  track_pop  
0       158436  169.837          2  
1       124000   79.509          1

group 14
[0.409 0.663 0.052 0.045 0.006 0.161 0.341 0.509 0.501 0.033]


track_name   artist_name                 album  danceability  \
0          Without You  John De Sohn           Without You         0.643   
1              What If         HOURS               What If         0.609   
2  Put Your Records On   Ritt Momney   Put Your Records On         0.399   
3   Right Here Waiting     Boostereo    Right Here Waiting         0.639   
4      Blinding Lights    The Weeknd       Blinding Lights         0.513   
5       Shooting Stars   Bag Raiders  Bag Raiders (Deluxe)         0.649   

   energy  speechiness  acousticness  instrumentalness  liveness  valence  \
0   0.745       0.0619       0.04490          0.000000    0.0916    0.461   
1   0.777       0.0353       0.00162          0.000001    0.0730    0.349   
2   0.492       0.0538       0.05800          0.001010    0.1100    0.159   
3   0.704       0.0352       0.06460          0.000000    0.4450    0.285   
4   0.796       0.0629       0.00147          0.000209    0.0938    0.345   
5   0.716       0.0445       0.08790          0.030000    0.0824    0.503   

   duration_ms    tempo  track_pop  
0       182613  124.968          0  
1       154286  126.001          0  
2       210463   91.066          1  
3       180522  115.052          0  
4       201573  171.017         18  
5       235813  124.968          0

group 15
[0.83  0.273 0.139 0.24  0.004 0.175 0.17  0.308 0.336 0.077]


track_name    artist_name             album  danceability  energy  \
0               AMG           Jt5k               AMG         0.802   0.509   
1  Calling My Phone       Lil Tjay  Calling My Phone         0.907   0.393   
2           Falling  Trevor Daniel           Falling         0.785   0.431   
3          Skechers     DripReport          Skechers         0.907   0.332   

   speechiness  acousticness  instrumentalness  liveness  valence  \
0       0.1810        0.0283          0.000000    0.3070   0.0567   
1       0.0539        0.4510          0.000001    0.1350   0.2020   
2       0.0364        0.1230          0.000000    0.0887   0.2360   
3       0.0836        0.3260          0.016800    0.1090   0.2770   

   duration_ms    tempo  track_pop  
0       135000   87.849          0  
1       205458  104.949         15  
2       159382  127.085         15  
3       106031   99.998          0

group 16
[0.735 0.517 0.661 0.396 0.    0.298 0.476 0.3   0.34  0.601]


track_name       artist_name  \
0   Enemy (with JID) - from the series Arcane Leag...   Imagine Dragons   
1               Chaa Chaa Chaa (feat. HoodCelebrityy)       Girll Codee   
2                                       Jiggle Jiggle      Duke & Jones   
3                                      Counting Stars             Farux   
4                                             RAPSTAR            Polo G   
5                             What You Know Bout Love         Pop Smoke   
6                            TKN (feat. Travis Scott)           ROSALÍA   
7                                            Over You            Myrrhe   
8                       FLIP THE SWITCH (feat. Drake)             Quavo   
9                                       Love Me Again               CPX   
10                      Don't Rush (feat. Headie One)  Young T & Bugsey   
11                                           Red Flag         Pia Baris   
12                                           Payphone       Faruk Orman   

                                                album  danceability  energy  \
0   Enemy (with JID) [from the series Arcane Leagu...         0.728   0.783   
1               Chaa Chaa Chaa (feat. HoodCelebrityy)         0.808   0.592   
2                                       Jiggle Jiggle         0.864   0.412   
3                                      Counting Stars         0.659   0.721   
4                                             RAPSTAR         0.789   0.536   
5                Shoot For The Stars Aim For The Moon         0.709   0.548   
6                            TKN (feat. Travis Scott)         0.776   0.509   
7                                            Over You         0.863   0.325   
8                                        QUAVO HUNCHO         0.853   0.637   
9                                       Love Me Again         0.798   0.824   
10                      Don't Rush (feat. Headie One)         0.961   0.461   
11                                           Red Flag         0.715   0.706   
12                                           Payphone         0.721   0.707   

    speechiness  acousticness  instrumentalness  liveness  valence  \
0         0.266         0.237          0.000000     0.434    0.555   
1         0.415         0.431          0.000000     0.426    0.628   
2         0.273         0.458          0.000870     0.124    0.654   
3         0.264         0.501          0.000000     0.109    0.454   
4         0.242         0.410          0.000000     0.129    0.437   
5         0.353         0.650          0.000002     0.133    0.543   
6         0.467         0.192          0.000001     0.115    0.485   
7         0.341         0.667          0.000017     0.100    0.537   
8         0.331         0.129          0.000000     0.267    0.496   
9         0.413         0.206          0.000308     0.436    0.242   
10        0.270         0.202          0.004020     0.162    0.324   
11        0.383         0.326          0.000231     0.525    0.348   
12        0.224         0.563          0.000006     0.338    0.462   

    duration_ms    tempo  track_pop  
0        173381   77.011         87  
1        185376  139.925         45  
2         97209   99.992         81  
3        144935  124.791         54  
4        165926   81.039         49  
5        160000   83.995         81  
6        129371   94.634         72  
7        126314   98.948         37  
8        156195   86.048         67  
9        134400  125.000         46  
10       207640  108.028         63  
11       137431  126.069         31  
12       128825  125.070         45

group 17
[0.603 0.293 0.117 0.752 0.167 0.141 0.521 0.303 0.325 0.716]


track_name        artist_name  \
0  Left and Right (Charlie Puth) [feat. Jung Kook...  sped up nightcore   
1                                 Pope Is a Rockstar              SALES   
2                                           I Hate U                SZA   
3                                       Running Away          VANO 3000   
4                                 Just The Two of Us            Kauai45   
5                                         Party Girl     StaySolidRocky   
6                                              Renee              SALES   

                                               album  danceability  energy  \
0  Left and Right (Charlie Puth) [feat. Jung Kook...         0.827   0.456   
1                                           SALES LP         0.725   0.446   
2                                           I Hate U         0.535   0.388   
3                                       Running Away         0.580   0.696   
4                                 Just The Two of Us         0.592   0.214   
5                                         Party Girl         0.728   0.431   
6                                              Renee         0.924   0.386   

   speechiness  acousticness  instrumentalness  liveness  valence  \
0       0.0942         0.622          0.000098    0.1090    0.689   
1       0.0287         0.850          0.243000    0.1070    0.311   
2       0.1550         0.507          0.000000    0.1100    0.412   
3       0.0408         0.660          0.852000    0.1450    0.721   
4       0.1150         0.936          0.000016    0.2530    0.422   
5       0.0622         0.749          0.000000    0.0996    0.629   
6       0.0548         0.755          0.002530    0.1180    0.424   

   duration_ms    tempo  track_pop  
0       135978  114.269         58  
1       187333   90.024         74  
2       174000  106.703         79  
3       111787   93.688         72  
4       117037   81.672         67  
5       147800  130.022         71  
6       179125  108.957         65

group 18
[0.564 0.769 0.106 0.187 0.015 0.273 0.146 0.338 0.462 0.534]


track_name    artist_name                         album  \
0                      Baby Girl    Disco Lines                     Baby Girl   
1                          Pepas        YES YES                         Pepas   
2                     Ocean Eyes          Farux                    Ocean Eyes   
3   Can't Get You Out of My Head        loafers  Can't Get You Out of My Head   
4                         Pieces      Nippandab                        Pieces   
5                 Paint It Black      Dame Dame                Paint It Black   
6              Free Falling Love  Lucas Estrada             Free Falling Love   
7                   Say It Right          MØRFI                  Say It Right   
8                          Creep        Naeleck                         Creep   
9                      Apologize          Farux                     Apologize   
10                   Lost on You      sad girls                   Lost on You   
11                 Glad You Came       Braaheim                 Glad You Came   
12                   Without You      Baby Bluu                   Without You   
13                  Falling Down    Andrew Nagy                  Falling Down   
14                     Only Girl         Coopex                     Only Girl   
15                     Old Times       Xtinctor                     Old Times   
16              Hey, Soul Sister          LANDR              Hey, Soul Sister   
17                        Demons            CPX                        Demons   
18                      Rockstar   Ilkay Sencan                      Rockstar   
19                        Lovely         Alfons                        Lovely   

    danceability  energy  speechiness  acousticness  instrumentalness  \
0          0.730   0.907       0.0606        0.0921          0.114000   
1          0.691   0.823       0.0626        0.0235          0.000000   
2          0.729   0.763       0.0345        0.6680          0.026400   
3          0.642   0.610       0.0992        0.1600          0.000007   
4          0.698   0.780       0.0626        0.1570          0.032500   
5          0.690   0.741       0.0363        0.0433          0.004290   
6          0.771   0.932       0.0424        0.3110          0.000158   
7          0.764   0.793       0.0709        0.0132          0.000980   
8          0.615   0.829       0.0421        0.0555          0.001560   
9          0.677   0.710       0.0552        0.5320          0.000000   
10         0.599   0.692       0.0739        0.1240          0.000000   
11         0.732   0.919       0.1150        0.0271          0.000866   
12         0.625   0.698       0.1460        0.0107          0.000000   
13         0.574   0.852       0.0438        0.0320          0.070500   
14         0.792   0.832       0.0397        0.3670          0.001640   
15         0.581   0.718       0.0851        0.0195          0.000000   
16         0.642   0.725       0.0571        0.1920          0.000000   
17         0.700   0.848       0.2170        0.3170          0.000000   
18         0.771   0.826       0.0604        0.1420          0.030000   
19         0.504   0.677       0.0640        0.3160          0.001270   

    liveness  valence  duration_ms    tempo  track_pop  
0     0.2300   0.2490       111074  120.968         76  
1     0.0781   0.1490       134330  125.973         58  
2     0.1470   0.1130       137029  125.989         42  
3     0.4080   0.2940       168000  129.886         52  
4     0.3090   0.2030       177956  122.076         42  
5     0.0975   0.0774       146190  125.985         56  
6     0.1160   0.1390       155000  120.012         58  
7     0.3190   0.1270       129677  124.084         50  
8     0.4260   0.0754       203226  124.013         65  
9     0.3370   0.3250       129410  126.109         48  
10    0.3750   0.3070       144349  121.796         53  
11    0.3750   0.1360       190879  125.997         48  
12    0.1560   0.2040       132625  120.119  

group 19
[0.649 0.515 0.619 0.119 0.004 0.169 0.491 0.453 0.789 0.741]


track_name          artist_name  \
0                          TO THE MOON             Jnr Choi   
1                            Long Road        HotBlock Jmoe   
2                         Light Switch         Charlie Puth   
3                           I AM WOMAN            Emmy Meli   
4                                MONEY                 LISA   
5                            So Pretty        Reyanna Maria   
6             When Hello Means Goodbye       Alex Alexander   
7                                Hawái               Maluma   
8   Gravity (feat. Tyler, The Creator)         Brent Faiyaz   
9      WAP (feat. Megan Thee Stallion)              Cardi B   
10        Mood Swings (feat. Lil Tjay)            Pop Smoke   
11                              Savage  Megan Thee Stallion   
12          Life Is Good (feat. Drake)               Future   
13         OUT WEST (feat. Young Thug)             JACKBOYS   

                                   album  danceability  energy  speechiness  \
0                            TO THE MOON         0.745   0.650        0.346   
1                              Long Road         0.738   0.685        0.409   
2            Light Switch (Instrumental)         0.690   0.626        0.306   
3                             I AM WOMAN         0.646   0.471        0.157   
4                                 LALISA         0.831   0.554        0.218   
5                              So Pretty         0.799   0.543        0.240   
6                              On My Way         0.741   0.475        0.205   
7                           PAPI JUANCHO         0.783   0.727        0.389   
8     Gravity (feat. Tyler, The Creator)         0.539   0.615        0.252   
9        WAP (feat. Megan Thee Stallion)         0.935   0.454        0.375   
10  Shoot For The Stars Aim For The Moon         0.480   0.602        0.368   
11                                  Suga         0.843   0.741        0.334   
12            Life Is Good (feat. Drake)         0.676   0.609        0.481   
13                              JACKBOYS         0.802   0.591        0.225   

    acousticness  instrumentalness  liveness  valence  duration_ms    tempo  \
0         0.0451          0.007580    0.1110    0.386       152137  144.047   
1         0.1350          0.000000    0.4000    0.663       204000  162.039   
2         0.1050          0.000335    0.0881    0.912       185681  184.009   
3         0.1220          0.000000    0.1250    0.455       232813  170.084   
4         0.1610          0.000061    0.1520    0.396       168228  140.026   
5         0.0512          0.042500    0.1340    0.250        85742  187.906   
6         0.0214          0.000000    0.3510    0.597       158160  166.016   
7         0.1850          0.000025    0.0626    0.558       199112  180.067   
8         0.1730          0.005600    0.1440    0.493       214693  163.924   
9         0.0194          0.000000    0.0824    0.357       187541  133.073   
10        0.4870          0.000000    0.0848    0.269       213333  179.798   
11        0.0252          0.000000    0.0960    0.680       155497  168.983   
12        0.0706          0.000000    0.1520    0.508       237735  142.037   
13        0.0104          0.000000    0.1960    0.309       157712  139.864   

    track_pop  
0          79  
1          52  
2          79  
3          76  
4          79  
5          66  
6          44  
7          77  
8          72  
9          80  
10         78  
11         70  
12         77  
13         77